### PR TITLE
Update v4.2.5

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### **djangorestframework-stubs and django-stubs now support mypy >=1.6.0**
**In Order to update to mypy>1.6.0**

> We need django-stubs-ext-feedstock to be first updated to v4.2.5
> Once django-stubs-ext-feedstock is updated to v4.2.5 and available on conda-forge
> django-stubs feedstock and jangorestframework-stubs feedstock can be updated

Dependency Tree and Sequence Required
1. https://github.com/conda-forge/django-stubs-ext-feedstock/pull/11
2. https://github.com/conda-forge/django-stubs-feedstock/pull/21
3. https://github.com/conda-forge/djangorestframework-stubs-feedstock/pull/14

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@thewchan - I have updated the title of this PR to reflect the steps required to enable the use of mypy>=1.6.0
and opened the corresponding PRs

Dependency Tree and Sequence Required
1. https://github.com/conda-forge/django-stubs-ext-feedstock/pull/11
2. https://github.com/conda-forge/django-stubs-feedstock/pull/21
3. https://github.com/conda-forge/djangorestframework-stubs-feedstock/pull/14

I am happy to help by being a co-maintainer - Please let me know if you would like me to raise a request add myself to the feedstocks. 

Thank you and Regards

**Comment by thewchan** [comment]
@rxm7706 Thanks so much; I went ahead and merged the automatic version instead just to keep it clean but please feel free to PR and add yourself as maintainer!

**Comment by rxm7706** [comment]
Perfect ! thank you for https://github.com/conda-forge/django-stubs-feedstock/pull/21 please note that the source requirement has changed to be  - django-stubs-ext >=4.2.5 ; so please use my PR / vs the bot . 
I will raise a request to get added as a maintainer once we have all these PR's merged.
Thanks

**Comment by rxm7706** [comment]
@thewchan Sorry I just noticed that you merged the bot version of django-stubs-feedstock & djangorestframework-stubs-feedstock - which is missing the source change of https://github.com/typeddjango/django-stubs/blob/4.2.5/setup.py#L26
I will fix that later. Thank you.

**Comment by thewchan** [comment]
@rxm7706 you don't have to do that, I've already updated the bot's branch of the recipe before merging.

**Comment by rxm7706** [comment]
> @rxm7706 you don't have to do that, I've already updated the bot's branch of the recipe before merging.

I see it ! Great. I have everything I need for now. Going to Upgrade my code base and see how things pan out. Appreciate the prompt responses and the time taken to fix and explain !

**Pull request closed without merging**
